### ISSUE TITLE
Got an error after clicking "Generate Planned Interrupted Buildings"

### ISSUE THREAD

**Issue by Prohodchikoff** [WebUraXalys/blackout#22]
```
Traceback (most recent call last):
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/admin_extra_buttons/handlers.py", line 77, in __call__
    return super().__call__(model_admin, request, *args, **kwargs)
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/admin_extra_buttons/handlers.py", line 50, in __call__
    ret = self.func(model_admin, request, *args, **kwargs)
  File "/home/dmytro/Documents/Project/blackout/blackout/parserapp/admin.py", line 51, in generate_planned_interrupted_buildings
    generate_planned_interrupted_buildings()
  File "/home/dmytro/Documents/Project/blackout/blackout/parserapp/services/generators.py", line 56, in generate_planned_interrupted_buildings
    plan_interruption = Interruptions.objects.get(Type="Plan")
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/models/query.py", line 653, in get
    raise self.model.MultipleObjectsReturned(
parserapp.models.Interruptions.MultipleObjectsReturned: get() returned more than one Interruptions -- it returned 2!
```

**Comment by Ferkkkk** [comment]
https://github.com/WebUraXalys/blackout/pull/21/commits/cbf7e1ab906b690c4a7d2b8efd222db206582708
