### ISSUE TITLE
Got an error after deleting a street with pk 1

### ISSUE THREAD

**Issue by Prohodchikoff** [WebUraXalys/blackout#26]
https://stackoverflow.com/questions/54655757/django-db-utils-integrityerror-foreign-key-constraint-failed
```
Internal Server Error: /admin/parserapp/buildings/generate_planned_interrupted_buildings/
Traceback (most recent call last):
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/admin_extra_buttons/handlers.py", line 77, in __call__
    return super().__call__(model_admin, request, *args, **kwargs)
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/admin_extra_buttons/handlers.py", line 50, in __call__
    ret = self.func(model_admin, request, *args, **kwargs)
  File "/home/dmytro/Documents/Project/blackout/blackout/parserapp/admin.py", line 51, in generate_planned_interrupted_buildings
    generate_planned_interrupted_buildings()
  File "/home/dmytro/Documents/Project/blackout/blackout/parserapp/services/generators.py", line 72, in generate_planned_interrupted_buildings
    building_obj.save()
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1671, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/backends/base/operations.py", line 212, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/utils.py", line 97, in inner
    with self:
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/dmytro/Documents/Project/proj/lib/python3.10/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
[20/May/2023 22:37:45] "GET /admin/parserapp/buildings/generate_planned_interrupted_buildings/? HTTP/1.1" 500 144050
```

**Comment by Ferkkkk** [comment]
https://github.com/WebUraXalys/blackout/pull/21/commits/cbf7e1ab906b690c4a7d2b8efd222db206582708
